### ISSUE TITLE
Export the latex to pdf

### ISSUE THREAD

**Issue by evenstensberg** [amaan-bhati/resume#1]
If you export the latex to pdf more people will get interested in your project :)

**Comment by amaan-bhati** [comment]
That's a great input @evenstensberg will upload it on Google drive as a pdf and add the drive link in the about section of the repo, what do you think?

**Comment by evenstensberg** [comment]
Just add the pdf in this repo

**Comment by amaan-bhati** [comment]
Done with it, thanks for the suggestion. Added both the pdf in the repo and also the drive link to the resume. Also gave you a shoutout in the commit message for your input:)

**Comment by evenstensberg** [comment]
Super!
